version: '3.8'

services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: unless-stopped
    volumes:
      - ./pterodactyl/panel-config:/app/config
      - ./pterodactyl/panel-config/var:/app/var
    ports:
      - "8080:80"
    networks:
      - mcnet
    depends_on:
      - panel_db
      - panel_redis

  panel_db:
    image: mariadb:10.6
    container_name: pterodactyl_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pterodactyl/panel-config/db_data:/var/lib/mysql
    networks:
      - mcnet

  panel_redis:
    image: redis:alpine
    container_name: pterodactyl_redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./pterodactyl/panel-config/redis_data:/data
    networks:
      - mcnet

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: unless-stopped
    privileged: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pterodactyl/wings-config:/etc/pterodactyl
      - ./pterodactyl/wings-config/var:/var/lib/pterodactyl
    networks:
      - mcnet
    depends_on:
      - panel
      - panel_db

networks:
  mcnet:
    external: true
